import datetime 
import jwt
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework import status
from codeone.settings import *
from home.helperservices import UpadteUserSolvedQuestion,UpadteSqlQuestion,UpateUserPoint,CalculateGlobalLeaderBoard,CalculateGlobalRankFuntion,ChangePassword,UserType,CheckUserNameAvailability,SendMail,CheckCurrentPassword,CheackValidToken,CheckUserVerification,GenerateToken,SendForgotPasswordToken,SendhackathonRegistrationMail,SendMailToLeads
from home.serializer import UserRegistrationSerilalizer,LeaderBoardSerializer,CodingQuestionSerializer,SqlQuestionsSerializer,SolvedQuestionSerializer,HackaThonSerializer,HackaThonRegistrationSerializer,hackathonProblemStatementSerializer,HackathonProblemTeamserializer,HackathonJudgeSerializer,EvaluationCriteriaSerializer
from home.models import *
from django.contrib.auth import authenticate
from home.compiler import *
from django.db import connection
import json