# Generated by Django 5.2.6 on 2025-12-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpUserRegistraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isadmin', models.BooleanField(default=False)),
                ('isuser', models.BooleanField(default=False)),
                ('isactive', models.BooleanField(default=False)),
                ('isverified', models.BooleanField(default=False)),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_question', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='HackaThon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organizer_name', models.CharField(max_length=200)),
                ('number_of_teams', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_deadline', models.DateTimeField()),
                ('is_registration_open', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackaThonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_id', models.CharField(max_length=50)),
                ('hackathon_name', models.TextField()),
                ('member_name', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_type', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('team_name', models.TextField()),
                ('college_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question_id', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=200)),
                ('quiz_question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('quiz_id', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('quiz_id', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('attempted_questions', models.PositiveIntegerField(default=0)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='solved', max_length=20)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('user_code', models.TextField(default='')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedSqlQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='solved', max_length=20)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SqlQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sql_question', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('expected_output', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='UserRegistraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isadmin', models.BooleanField(default=False)),
                ('isuser', models.BooleanField(default=False)),
                ('isactive', models.BooleanField(default=False)),
                ('isverified', models.BooleanField(default=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersCodingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('SolvedCodingQuestion', models.PositiveBigIntegerField(default=0)),
                ('mediumquesitons', models.PositiveBigIntegerField(default=0)),
                ('easyquesitons', models.PositiveBigIntegerField(default=0)),
                ('hardquestions', models.PositiveBigIntegerField(default=0)),
                ('globalrank', models.PositiveSmallIntegerField(default=0)),
                ('solvedquestion', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='hackathonProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('number_of_team', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='HackathonProblemTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathonregistration')),
                ('problem_statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathonproblemstatement')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('testcasepoint', models.PositiveIntegerField(default=10)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_test_cases', to='home.codingquestion')),
            ],
        ),
    ]
