# Generated by Django 5.1 on 2025-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistraion',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userregistraion',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistraion',
            name='isuser',
            field=models.BooleanField(default=True),
        ),
    ]
