# Generated by Django 5.2.6 on 2025-12-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonregistration',
            name='team_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
