# Generated by Django 5.2.6 on 2025-12-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hackathonregistration_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonproblemstatement',
            name='max_number_of_team',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
