# Generated by Django 5.1 on 2025-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userregistraion_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistraion',
            name='isuser',
            field=models.BooleanField(default=False),
        ),
    ]
