# Generated by Django 5.2.6 on 2025-12-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hackathonproblemstatement_max_number_of_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='team_id',
            field=models.TextField(),
        ),
    ]
