# Generated by Django 5.1 on 2025-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userregistraion_isuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistraion',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
