# Generated by Django 5.2.6 on 2025-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hackathonproblemteam_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='problem_statement_id',
            field=models.CharField(max_length=200),
        ),
    ]
