# Generated by Django 5.2.6 on 2025-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hackathonproblemteam_problem_statement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='hackathon_id',
            field=models.TextField(),
        ),
    ]
