# Generated by Django 5.1 on 2025-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_question_id_sampletestcase_coding_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='coding_question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='title',
            field=models.TextField(),
        ),
    ]
