# Generated by Django 5.2.6 on 2025-12-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_hackathonproblemteam_hackathon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='hackathon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon'),
        ),
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='problem_statement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathonproblemstatement'),
        ),
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathonregistration'),
        ),
    ]
