# Generated by Django 5.1 on 2025-06-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_codingquestion_coding_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
