# Generated by Django 5.2.6 on 2025-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_hackathonproblemteam_hackathon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonproblemteam',
            name='team_id',
            field=models.TextField(),
        ),
    ]
