# Generated by Django 6.0.3 on 2026-06-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_hackathonproblemteam_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonregistration',
            name='member_type',
            field=models.CharField(choices=[('member', 'Member'), ('leader', 'Leader')], max_length=20),
        ),
        migrations.CreateModel(
            name='HackathonJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistraion')),
            ],
        ),
    ]
