# Generated by Django 5.1 on 2025-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_codingquestion_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpUserRegistraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isadmin', models.BooleanField(default=False)),
                ('isuser', models.BooleanField(default=False)),
                ('isactive', models.BooleanField(default=False)),
                ('isverified', models.BooleanField(default=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
