# Generated by Django 6.0.7 on 2026-07-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_hackathonregistration_member_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='created_by_user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.userregistraion'),
        ),
    ]
