# Generated by Django 5.1 on 2025-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_backupuserregistraion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupuserregistraion',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
