# Generated by Django 6.0.7 on 2026-07-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_hackathon_created_by_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='created_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userregistraion'),
        ),
    ]
