# Generated by Django 5.1 on 2025-06-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_backupuserregistraion_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCodingPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiestName', models.CharField(max_length=90)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='home.userregistraion')),
            ],
        ),
    ]
