# Generated by Django 5.1 on 2025-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userscodingpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscodingpoints',
            name='fiestName',
        ),
        migrations.AddField(
            model_name='userscodingpoints',
            name='easyquesitons',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscodingpoints',
            name='hardquestions',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscodingpoints',
            name='mediumquesitons',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscodingpoints',
            name='points',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscodingpoints',
            name='solvedquestion',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscodingpoints',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
