# Generated by Django 6.0.7 on 2026-07-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_hackathon_created_by_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackaThonMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveBigIntegerField(default=0)),
                ('title', models.TextField()),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('hackthon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathonregistration')),
            ],
        ),
    ]
