# Generated by Django 6.0.7 on 2026-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hackathonmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonmarks',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathonmarks',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
