# Generated by Django 5.1 on 2025-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_userscodingpoints_fiestname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscodingpoints',
            name='globalrank',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
