# Generated by Django 5.1 on 2025-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userscodingpoints_globalrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletestcase',
            name='testcasepoint',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userscodingpoints',
            name='globalrank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
