# Generated by Django 6.0.7 on 2026-07-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hackathonmarks_description_hackathonmarks_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hackathon')),
            ],
        ),
        migrations.AddField(
            model_name='hackathonmarks',
            name='criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.evaluationcriteria'),
            preserve_default=False,
        ),
    ]
