# Generated by Django 5.1 on 2025-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sampletestcase_testcasepoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('coding_question', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='solved', max_length=20)),
            ],
        ),
    ]
