# Generated by Django 5.1 on 2025-06-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_solvedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedquestion',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='solvedquestion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='solvedquestion',
            name='solved_at',
        ),
        migrations.RemoveField(
            model_name='solvedquestion',
            name='title',
        ),
    ]
