# Generated by Django 5.1 on 2025-06-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_solvedquestion_constraints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedquestion',
            old_name='coding_question',
            new_name='question_id',
        ),
    ]
