# Generated by Django 5.1 on 2025-06-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_coding_question_solvedquestion_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedquestion',
            old_name='question_id',
            new_name='coding_question',
        ),
    ]
