# Generated by Django 5.1 on 2025-06-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_question_id_solvedquestion_coding_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedquestion',
            old_name='coding_question',
            new_name='question_id',
        ),
        migrations.RemoveField(
            model_name='solvedquestion',
            name='difficulty',
        ),
    ]
