# Generated by Django 5.1 on 2025-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_coding_question_solvedquestion_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedquestion',
            name='points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
