# Generated by Django 5.1 on 2025-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_solvedquestion_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
