# Generated by Django 5.1 on 2025-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_employeedata_sqlquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedSqlQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='solved', max_length=20)),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
            ],
        ),
    ]
