# Generated by Django 5.1 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_solvedsqlquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscodingpoints',
            name='solvedquestion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
