# Generated by Django 5.1 on 2025-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_userscodingpoints_solvedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedquestion',
            name='user_code',
            field=models.TextField(default=''),
        ),
    ]
