# Generated by Django 5.2.6 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_quiz_quizanswer_quizquestion_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('quiz_id', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
