# Generated by Django 5.2.6 on 2025-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_quizregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizregistration',
            name='quiz_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
