# Generated by Django 5.2.6 on 2025-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_quizregistration_quiz_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizregistration',
            name='quiz_number',
        ),
        migrations.AddField(
            model_name='quizregistration',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizregistration',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
