# Generated by Django 5.2.6 on 2025-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_quizregistration_quiz_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackaThon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organizer_name', models.CharField(max_length=200)),
                ('number_of_teams', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_deadline', models.DateTimeField()),
            ],
        ),
    ]
