# Generated by Django 5.2.6 on 2025-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_hackathon_is_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
