# Generated by Django 5.2.6 on 2025-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_hackathon_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackaThonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('hackathon_id', models.CharField(max_length=50)),
                ('hackathon_name', models.TextField()),
                ('member_name', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_type', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('team_name', models.TextField()),
                ('college_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField()),
            ],
        ),
    ]
