# Generated by Django 5.2.6 on 2025-10-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_hackathonregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
